### ISSUE TITLE
save/state filename

### ISSUE THREAD

**Issue by soundsnow** [JoppyFurr/Snepulator#15]
Create a folder for save files
Create a folder for state files
because more files costs more time to scan

This is a state file
175a136ace3d74867f6f4b03.save01

Why you call that save?
That's a state
If all state slots 10
the number should be 0 to 9

175a136ace3d74867f6f4b03.sta1

What game?

Hero (My Country).sg
Hero (My Country).sta9
Hero (My Country).sav

**Comment by JoppyFurr** [comment]
These files are internal to the emulator and are not intended to be used directly by users.

I have never been a fan of emulators that store their save files in the same directory as the user's rom collection.
