### ISSUE TITLE
I am the first user of snepulator sg

### ISSUE THREAD

**Issue by soundsnow** [JoppyFurr/Snepulator#2]
I take the liberty of requesting a free version of snepulator ms.  Publish it on github and keep it closed source.  Why?  I'm sure no one is more active in submitting emulator-related issues than I am, especially the unpopular console emulator on Android.  And very unfortunately, China, where I live, blocks a lot of foreign websites, and I am forced to not be able to pay you.  I test Android emulators more aggressively than anyone else, and they often take my time off from eating and sleeping.  snepulator sg is the apk that I entrusted a friend to download and send to me
https://emulation.gametechwiki.com/index.php/SG-1000_emulators
https://emulation.gametechwiki.com/index.php/Master_System_emulators
https://emulation.gametechwiki.com/index.php/ColecoVision_emulators
https://emulation.gametechwiki.com/index.php/Emulators_on_Android
I added your emulator to the Emulation General Wiki list, it should get more attention.  Next I will submit a lot of improvements.  But it's better if you can provide regular stable apk in Github Release, otherwise I can't submit improvements, bugs and suggestions for it.  I'm sorry I have money, but China doesn't allow me to help you with this.  Because I am sincere, I will make such an excessive request.  I just wish the emulators on Android were better, I don't have that much time to play games, most of the time I use to test emulators

You can first look at the open and closed [issues](https://github.com/PhilPotter/MasterEmu/issues) I posted on MasterEmu 
I don't have that much time now

I will post issues about this emulator one by one, MasterEmu's issues as a supplement, lest I forget some of them

Reasons to request a free version of snepulator ms
1. Android emulator tester
2. The phone has Gapps removed or Custom ROM installed
3. It is not possible to transfer money abroad through legal means in the area where I live

**Comment by soundsnow** [comment]
Please don't delete this issue, I will send out my suggestions and bugs as soon as possible.  Because I know you have deleted an issue

**Comment by JoppyFurr** [comment]
I am sorry about your situation. It sucks that their are countries out there with such restrictions.

I have been working on Snepulator for the past six years, posting the PC version up here on GitHub free and open source. The android port I have made is an attempt to try get something back for the time I have put into the project. Publishing a free copy of the full Android version is not something I intend to do in the foreseeable future.
