### ISSUE TITLE
BIOS

### ISSUE THREAD

**Issue by soundsnow** [JoppyFurr/Snepulator#5]
[BIOS] ColecoVision (USA, Europe).col
[BIOS] Othello Multivision (Japan).sg
[BIOS] Alex Kidd in Miracle World (BIOS Version) (World) (Sega Ages).sms
[BIOS] Alex Kidd in Miracle World (Korea) (Unl).sms
[BIOS] Alex Kidd in Miracle World (USA, Europe).sms
[BIOS] Hang On & Safari Hunt (USA, Europe, Brazil) (En) (v2.4).sms
[BIOS] Missile Defense 3-D (USA, Europe) (v4.4).sms
[BIOS] Sega Master System (Europe) (v2.0).sms
[BIOS] Sega Master System (Japan) (v2.1).sms
[BIOS] Sega Master System (USA) (M404) (Proto).sms
[BIOS] Sega Master System (USA) (Store Display Unit).sms
[BIOS] Sega Master System (USA) (v1.0) (Proto).sms
[BIOS] Sega Master System (USA, Europe) (v1.3).sms
[BIOS] Sonic The Hedgehog (Europe).sms
[BIOS] Sega Game Gear (USA) (Majesco).gg

COL - Bit Corporation Dina
czz50-1.rom + czz50-2.rom
COL - ColecoVision
coleco.rom
COL - ColecoVision with Opcode Memory Extension
coleco.rom
COL - Spectravideo SVI-603 Coleco
SVI603.ROM
SEGA - SF-7000
sf7000.rom

bios.gg
bios_E.sms
bios_J.sms
bios_U.sms

**Comment by JoppyFurr** [comment]
This is not an issue, but a list of filenames. Closing.
