### ISSUE TITLE
Sega and Coleco Machines

### ISSUE THREAD

**Issue by soundsnow** [JoppyFurr/Snepulator#6]
SEGA - SG-1000
SEGA - SC-3000
SEGA - SF-7000
COL - Bit Corporation Dina
COL - ColecoVision
COL - ColecoVision with Opcode Memory Extension
COL - Spectravideo SVI-603 Coleco

I did not add Coleco Adam

**Comment by JoppyFurr** [comment]
This is not an issue, just a list of consoles.
